[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"
[project]
name = "thinking-machine"
version = "0.0.4"
authors = [
    {name="Alexander Fedotov", email="alex.fedotov@aol.com"},
]
description = "Thinking machine is a machine that thinks."
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]

keywords = ["package-name"]

dependencies = [
    "PyGithub >= 2.6.0",
    "PyYAML >= 6.0.1",
    "urllib3 >= 2.0.4",
    "requests >= 2.32.3",
    "click >= 8.3.0"
]

[project.scripts]
package-name = "thinking_machine.cli:run"

[project.urls]
"Homepage" = "https://github.com/machina-ratiocinatrix/thinking-machine"
"Bug Tracker" = "https://github.com/machina-ratiocinatrix/thinking-machine/issues"